version: '3.8'

services:
  nvim-0.10:
    build:
      context: .
      dockerfile: Dockerfile.nvim
      args:
        NVIM_VERSION: v0.10.2
    container_name: nvim-0.10
    volumes:
      - ./plugins:/root/.local/share/nvim/site/pack/test/start
      - ./test-config:/root/.config/nvim
    working_dir: /workspace
    tty: true
    stdin_open: true
    command: nvim

  nvim-0.11:
    build:
      context: .
      dockerfile: Dockerfile.nvim
      args:
        NVIM_VERSION: stable  # v0.11.1が現在の安定版
    container_name: nvim-0.11
    volumes:
      - ./plugins:/root/.local/share/nvim/site/pack/test/start
      - ./test-config:/root/.config/nvim
    working_dir: /workspace
    tty: true
    stdin_open: true
    command: nvim

  nvim-0.12-dev:
    build:
      context: .
      dockerfile: Dockerfile.nvim
      args:
        NVIM_VERSION: nightly  # v0.12.0-devの開発版
    container_name: nvim-0.12-dev
    volumes:
      - ./plugins:/root/.local/share/nvim/site/pack/test/start
      - ./test-config:/root/.config/nvim
    working_dir: /workspace
    tty: true
    stdin_open: true
    command: nvim