version: '3.8'

services:
  nvim-0.10:
    build:
      context: .
      dockerfile: Dockerfile.nvim
      args:
        NVIM_VERSION: v0.10.2
    container_name: nvim-0.10
    volumes:
      - ./plugins:/root/.local/share/nvim/site/pack/test/start
      - ./test-config:/root/.config/nvim
    working_dir: /workspace
    tty: true
    stdin_open: true
    command: nvim

  nvim-0.11:
    build:
      context: .
      dockerfile: Dockerfile.nvim
      args:
        NVIM_VERSION: nightly
    container_name: nvim-0.11
    volumes:
      - ./plugins:/root/.local/share/nvim/site/pack/test/start
      - ./test-config:/root/.config/nvim
    working_dir: /workspace
    tty: true
    stdin_open: true
    command: nvim

  nvim-stable:
    build:
      context: .
      dockerfile: Dockerfile.nvim
      args:
        NVIM_VERSION: stable
    container_name: nvim-stable
    volumes:
      - ./plugins:/root/.local/share/nvim/site/pack/test/start
      - ./test-config:/root/.config/nvim
    working_dir: /workspace
    tty: true
    stdin_open: true
    command: nvim